import 'package:flutter/material.dart';
import 'package:fimetlo/Categories/category.dart';
import 'package:fimetlo/meal.dart';
import 'package:fimetlo/Categories/meal_detail_screen.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Food',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
    image: "assets/download.png"
  ),
  Category(
    id: 'c2',
    title: 'Clothes',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
    image: "assets/download (1).png"
  ),
  Category(
    id: 'c3',
    title: 'Utilities',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
    image: "assets/287-2879349_utility-model-comments-utilities-icon.png"

  ),
  Category(
    id: 'c4',
    title: 'Health',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
    image: "assets/download (2).png"
 
  ),
  Category(
    id: 'c5',
    title: 'Pets',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
    image: "assets/download (3).png"
 
  ),
  Category(
    id: 'c6',
    title: 'Children',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
      image: "assets/download.jpg"

  ),
];

const DUMMY_MEALS = const [
  Meal(
      id: 'm1',
      categories: [
        'c1',
      ],
      title: 'Nutella Jar',
      Price: 5,
      imageUrl:
          'https://media.istockphoto.com/id/537609774/photo/jar-of-italian-nutella-hazelnuts-cream.jpg?s=612x612&w=0&k=20&c=5r09uQnkwcMHAvYJB1np9j2axqGlDPc75_anzktYTHY=',
      duration: 480,
      ingredients: [
        'Sourdough Starter',
        'Bread Flour',
        'Water',
        'Salt',
      ],
      availability: Availability.Available,
      rating: 0,
      steps: [
        ' Bread has crispy edges with a soft center.',
        ' Relatively light on stomach.',
        ' Add labneh and veggies to enhance the overall experience.',
      ],
      isGlutenFree: false,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
      Description: "Standard sized nutella Jar"),
  Meal(
    Description: "Standard sized frutella Jar",
    availability: Availability.Unvailable,
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Frutella Jar',
    Price: 5,
    imageUrl:
        'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/c/ecd16f7calle00000005_1.jpg',
    duration: 480,
    ingredients: [
      'Flour',
      'Water',
      'Yeast',
      'Salt',
    ],
    steps: [
      ' Use the bread for any type of sandwich.',
      ' Crispy all around and soft in the bottom.',
      ' Small and compact rectangular shape.'
    ],
    rating: 0,
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Standard sized Maxtella Jar",
    availability: Availability.Unvailable,
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'Maxtella jar',
    Price: 5,
    imageUrl: 'https://m.media-amazon.com/images/I/61yhCYOpJnL.jpg',
    duration: 480,
    ingredients: [
      'Flour',
      'Water',
      'Yeast',
      'Salt',
    ],
    rating: 0,
    steps: [
      " Infuse with oil to enhance the taste",
      " Bread is soft both on the inside and the outside.",
      "Ideally consumed with cheesey products."
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Standard sized Gurmex Jar",
    availability: Availability.Available,
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'Gurmex Jar',
    Price: 5,
    imageUrl:
        'https://cdnprod.mafretailproxy.com/sys-master-root/h77/h1f/9284309254174/325966_main.jpg_480Wx480H',
    duration: 180,
    ingredients: [
      'flour',
      'water',
      'yeast',
      'salt',
    ],
    rating: 0,
    steps: [
      ' Flat Bread with cripsy edges and a soft surface.',
      ' Relatively large in size and can be adjusted according to the costumer\s needs.',
      ' Bread has a multi variant use.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Medium barbecue chips bag",
    availability: Availability.Unvailable,
    id: 'm5',
    categories: ['c1'],
    title: 'Master Chips, Barbecue',
    Price: 5,
    imageUrl:
        'https://www.temafinefoods.com/wp-content/uploads/2022/10/7508.jpg',
    duration: 480,
    ingredients: [
      'Eggs',
      'milk',
      'Flour',
      'Sugar',
      'Butter',
      'Yeast',
      'Salt',
      'Powdered Milk',
    ],
    rating: 0,
    steps: [
      'Extremely soft both on the outside and the inside',
      'Bread has a sweet taste from the milk',
      'Can be filled with walnuts, dark chocolate, lotus and cinamon sugar',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
      Description: "Medium french cheese chips bag",
      availability: Availability.Available,
      id: 'm6',
      categories: [
        'c1',
      ],
      title: 'Master Chips, French Cheese',
      Price: 5,
      imageUrl:
          'https://www.temafinefoods.com/wp-content/uploads/2023/01/7509.jpg',
      duration: 120,
      ingredients: [
        'Butter',
        'White Sugar',
        'Brown Sugar',
        'Flour',
        'Eggs',
        'Vanilla',
        'Chocolate Chunks',
        'Baking Soda'
      ],
      steps: [
        ' Crisp edges with a soft center.',
        ' Served in a package of twelve pieces.',
        ' Can be consumed with milk on the side.',
      ],
      isGlutenFree: false,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: false,
      rating: 0),
  Meal(
    Description: "84 pieces patchi chocolates box",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm7',
    categories: [
      'c1',
    ],
    title: 'Patchi Box 84',
    Price: 5,
    imageUrl:
        "https://patchi.nyc3.cdn.digitaloceanspaces.com/patchi.com/public/data//products_gallery_600_600/6304e509b672d.jpg?v=4660?v=4660",
    duration: 60,
    ingredients: [
      'Eggs',
      'Milk',
      'Yogurt',
      'Oil',
      'Sugar',
      'Cacao',
      'Nescafe',
    ],
    steps: [
      ' Moisty and fluffy texture.',
      ' Minimum order of 6 pieces. (Additional pieces can be ordered).',
      ' Cupcakes can be stuffed with lotus, chocolate ganache and berry jam.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    Description: "12 pieces patchi macaron box",
    availability: Availability.Available,
    rating: 0,
    id: 'm8',
    categories: [
      'c1',
    ],
    title: 'Patchi Macaron Box',
    imageUrl:
        'https://patchi.nyc3.cdn.digitaloceanspaces.com/patchi.com/public/data//products_gallery/619634ede9956.jpg?v=3468',
    duration: 90,
    Price: 5,
    ingredients: [
      'Brown Sugar',
      'White Sugar',
      'Eggs',
      'Bananas',
      'Yogurt',
      'Milk',
      'Butter',
      'Oil',
      'Baking Soda',
      'Baking Powder',
      'Vanilla',
      'Cinnamon',
      'Flour',
      'Chocolate Chips'
    ],
    steps: [
      ' Very soft and moist cake',
      ' Can be consumed with tea',
      ' Tastes both chocolatey with a kick of banana and cinnamon taste',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    Description: "Lindt chocolate box",
    availability: Availability.Available,
    rating: 0,
    id: 'm9',
    categories: [
      'c1',
    ],
    title: 'One Lindt OatMilk Salted Caramel',
    Price: 5,
    imageUrl:
        'https://www.lindtusa.com/media/catalog/product/0/0/00009542438692_front.jpg?quality=80&fit=bounds&height=500&width=500&canvas=500:500',
    duration: 45,
    ingredients: ["Milk", "Flour", "Sugar", "Butter", "Eggs", "Yeast", "Salt"],
    steps: [
      " Extremely soft and milkey.",
      " Tastes leanes more on the sweet side",
      " Enhance experience by adding nutella, honey or butter.",
      " Similar dough is used to make chocolate buns, cinnamon rolls and cheese buns."
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    Description: "One Lindt chocolate box without sugar",
    availability: Availability.Available,
    rating: 0,
    id: 'm10',
    categories: ['c1'],
    title: 'Lindt No Sugar Added Chocolate Candy Bar',
    Price: 5,
    imageUrl:
        'https://www.lindtusa.com/media/catalog/product/0/0/00009542043995_front.png?quality=80&fit=bounds&height=500&width=500&canvas=500:500',
    duration: 180,
    ingredients: [
      'Bread Flour',
      'Corn Starch',
      'Sugar',
      'Yeast',
      'Potato Water',
      'Olive Oil',
      'Mashed Potatoes',
    ],
    steps: [
      ' Soft texture both on the outside and the inside',
      ' Mild olive oil taste',
      ' Minimum 6, 6 cm pieces (customer can add pieces for an additional price)',
      ' Can be grilled and dipped with your favorite vegan dip (hommous) or non vegan dip',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "A pair of Nike Air Jordan 1's",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm12',
    categories: ['c2'],
    title: 'Nike Air Jordan 1s',
    Price: 90,
    imageUrl:
        'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b093663e-817f-44d0-8cd3-5d53905c1a62/air-jordan-1-retro-high-og-shoes-fZMprq.png',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One red Ralph Lauren Polo",
    availability: Availability.Available,
    rating: 0,
    id: 'm13',
    categories: ['c2'],
    title: 'Ralph Lauren Polo',
    Price: 15,
    imageUrl:
        'https://www.repertoirefashion.co.uk/images/polo-ralph-lauren-mens-holiday-red-slim-fit-stretch-mesh-polo-shirt-p42129-249866_medium.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One Levi's high waisted jeans",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm14',
    categories: ['c2'],
    title: 'Levi\'s Jeans',
    Price: 25,
    imageUrl:
        'https://storage.sg.content-cdn.io/cdn-cgi/image/width=864,height=1440,quality=75,format=auto/in-resources/21e9ae3c-de72-4391-9c4a-c7af58447630/Images/ProductImages/Source/levis-womens-501-81-jeans-A46990006_15_Details.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "3 pairs of Massimo Dutti socks ",
    availability: Availability.Available,
    rating: 0,
    id: 'm15',
    categories: ['c2'],
    title: 'Massimo Dutti',
    Price: 10,
    imageUrl:
        'https://static.massimodutti.net/3/photos//2023/V/0/2/p/0692/052/800/0692052800_1_1_16.jpg?t=1678201311058&impolicy=massimodutti-itxmediumhigh&imwidth=400&imformat=chrome',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One big set of Screws",
    availability: Availability.Available,
    rating: 0,
    id: 'm16',
    categories: ['c3'],
    title: 'Screws',
    Price: 10,
    imageUrl:
        "https://www.newport.com/mam/celum/celum_assets/np/Setscrew-refill_400w.jpg?2",
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "30 watts usb c charger",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm17',
    categories: ['c3'],
    title: 'Charger',
    Price: 8,
    imageUrl:
        'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6445/6445193_sd.jpg;maxHeight=640;maxWidth=550',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One pack of duracell batteries",
    availability: Availability.Available,
    rating: 0,
    id: 'm18',
    categories: ['c3'],
    title: 'Duracell Batteries',
    Price: 10,
    imageUrl:
        'https://www.duracellsingapore.com/cdn/shop/products/202111_Duracell_Brenda_Productshot_800x800_v2-03_800x.jpg?v=1637546517',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Folding tripod antennna",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm19',
    categories: ['c3'],
    title: 'RFID Tripod',
    Price: 54,
    imageUrl:
        "https://cdn11.bigcommerce.com/s-ka7ofex/images/stencil/640w/products/1884/10544/Vulcan_RFID_Folding_Tripod__45995.1626801785.PNG?c=2",
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One 12 pack paracetamol",
    availability: Availability.Available,
    rating: 0,
    id: 'm20',
    categories: ['c4'],
    title: 'Panadol Pills',
    Price: 12,
    imageUrl:
        'https://i-cf65.ch-static.com/content/dam/cf-consumer-healthcare/panadol-reborn/en_ME/product-detail/panadol-advance/Panadol%20Advance%20LF%20380x463.png?auto=format',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "One capsule of advil liquid jel",
    availability: Availability.Available,
    rating: 0,
    id: 'm21',
    categories: ['c4'],
    title: 'Advil liquid kel',
    Price: 13,
    imageUrl: 'https://m.media-amazon.com/images/I/81ahmfrDP-L.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Benadryl Cough syrup for cough treatments",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm22',
    categories: ['c4'],
    title: 'Benadryl Syrup',
    Price: 18,
    imageUrl:
        'https://newassets.apollo247.com/pub/media/catalog/product/b/e/ben0006_2.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Motelium Pills to fix stomach pain ",
    availability: Availability.Available,
    rating: 0,
    id: 'm23',
    categories: ['c4'],
    title: 'Motelium Pills',
    Price: 9,
    imageUrl:
        'https://cdn.shopify.com/s/files/1/2270/7227/products/Motilium10mgTablets30s.jpg?v=1662113658',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Dry dog food for adults dogs ",
    availability: Availability.Available,
    rating: 0,
    id: 'm24',
    categories: ['c5'],
    title: 'Pedigree Dog Food',
    Price: 30,
    imageUrl: 'https://m.media-amazon.com/images/I/61IUJIyK2yL.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Lightweight dog harness",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm25',
    categories: ['c5'],
    title: 'Dog harness',
    Price: 76,
    imageUrl:
        'https://cdn.shopify.com/s/files/1/0895/6922/products/Front-Range-Harness-Aurora-Teal-Right-1024_800x.jpg?v=1613532923',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Cat anti fleas collar",
    availability: Availability.Available,
    rating: 0,
    id: 'm26',
    categories: ['c5'],
    title: 'Cat collar',
    Price: 25,
    imageUrl:
        'https://assets.petco.com/petco/image/upload/f_auto,q_auto/3329514-center-1',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Cat house medium sized ",
    availability: Availability.Unvailable,
    rating: 0,
    id: 'm27',
    categories: ['c5'],
    title: 'Cat House',
    Price: 150,
    imageUrl:
        'https://5.imimg.com/data5/SELLER/Default/2021/3/CJ/QH/BK/124991817/wooden-cat-house-small--1000x1000.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Lego technique set for kids",
    availability: Availability.Available,
    rating: 0,
    id: 'm28',
    categories: ['c6'],
    title: 'Lego Technique',
    Price: 449,
    imageUrl:
        'https://www.lego.com/cdn/cs/set/assets/bltee88e5e65f00bd00/42115.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Playstation 5 console with 2 controllers",
    availability: Availability.Available,
    rating: 0,
    id: 'm29',
    categories: ['c6'],
    title: 'Playstation 5',
    Price: 10,
    imageUrl:
        'https://cdn11.bigcommerce.com/s-sp9oc95xrw/images/stencil/608x608/products/3812/25146/6426149cv13d__84984.1653561814.jpg?c=2',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Nintendo switch with the full set ",
    availability: Availability.Available,
    rating: 0,
    id: 'm30',
    categories: ['c6'],
    title: 'Nintendo Switch',
    Price: 299,
    imageUrl:
        'https://assets.nintendo.com/image/upload/f_auto/q_auto/c_fill,w_800/ncom/en_US/switch/system/three-modes-in-one',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    Description: "Xbox one X with two controllers ",
    availability: Availability.Available,
    rating: 0,
    id: 'm31',
    categories: ['c6'],
    title: 'Xbox one X',
    Price: 399,
    imageUrl: 'https://m.media-amazon.com/images/I/61ux1cU49XL._SX522_.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
];