import 'package:flutter/material.dart';
import 'package:fimetlo/From_mimi/category.dart';
import 'package:fimetlo/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Food',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
  Category(
    id: 'c2',
    title: 'Clothes',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
  Category(
    id: 'c3',
    title: 'Utilities',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
  Category(
    id: 'c4',
    title: 'Health',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
  Category(
    id: 'c5',
    title: 'Pets',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
  Category(
    id: 'c6',
    title: 'Children',
    color: Color.fromARGB(255, 255, 255, 255),
    textcolor: Color.fromARGB(255, 255, 255, 255),
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Nutella Jar',
    Price: 5,
    imageUrl:
        'https://media.istockphoto.com/id/537609774/photo/jar-of-italian-nutella-hazelnuts-cream.jpg?s=612x612&w=0&k=20&c=5r09uQnkwcMHAvYJB1np9j2axqGlDPc75_anzktYTHY=',
    duration: 480,
    ingredients: [
      'Sourdough Starter',
      'Bread Flour',
      'Water',
      'Salt',
    ],
    availability: Availability.Available,
    rating: 3.5,
    steps: [
      ' Bread has crispy edges with a soft center.',
      ' Relatively light on stomach.',
      ' Add labneh and veggies to enhance the overall experience.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Unvailable,
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Frutella Jar',
    Price: 5,
    imageUrl:
        'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/c/ecd16f7calle00000005_1.jpg',
    duration: 480,
    ingredients: [
      'Flour',
      'Water',
      'Yeast',
      'Salt',
    ],
    steps: [
      ' Use the bread for any type of sandwich.',
      ' Crispy all around and soft in the bottom.',
      ' Small and compact rectangular shape.'
    ],
    rating: 3.5,
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Unvailable,
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'Maxtella jar',
    Price: 5,
    imageUrl: 'https://m.media-amazon.com/images/I/61yhCYOpJnL.jpg',
    duration: 480,
    ingredients: [
      'Flour',
      'Water',
      'Yeast',
      'Salt',
    ],
    rating: 3.5,
    steps: [
      " Infuse with oil to enhance the taste",
      " Bread is soft both on the inside and the outside.",
      "Ideally consumed with cheesey products."
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Available,
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'Gurmex Jar',
    Price: 5,
    imageUrl:
        'https://cdnprod.mafretailproxy.com/sys-master-root/h77/h1f/9284309254174/325966_main.jpg_480Wx480H',
    duration: 180,
    ingredients: [
      'flour',
      'water',
      'yeast',
      'salt',
    ],
    rating: 3.5,
    steps: [
      ' Flat Bread with cripsy edges and a soft surface.',
      ' Relatively large in size and can be adjusted according to the costumer\s needs.',
      ' Bread has a multi variant use.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Unvailable,
    id: 'm5',
    categories: ['c1'],
    title: 'Master Chips, Barbecue',
    Price: 5,
    imageUrl:
        'https://www.temafinefoods.com/wp-content/uploads/2022/10/7508.jpg',
    duration: 480,
    ingredients: [
      'Eggs',
      'milk',
      'Flour',
      'Sugar',
      'Butter',
      'Yeast',
      'Salt',
      'Powdered Milk',
    ],
    rating: 3.5,
    steps: [
      'Extremely soft both on the outside and the inside',
      'Bread has a sweet taste from the milk',
      'Can be filled with walnuts, dark chocolate, lotus and cinamon sugar',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
      availability: Availability.Available,
      id: 'm6',
      categories: [
        'c1',
      ],
      title: 'Master Chips, French Cheese',
      Price: 5,
      imageUrl:
          'https://www.temafinefoods.com/wp-content/uploads/2023/01/7509.jpg',
      duration: 120,
      ingredients: [
        'Butter',
        'White Sugar',
        'Brown Sugar',
        'Flour',
        'Eggs',
        'Vanilla',
        'Chocolate Chunks',
        'Baking Soda'
      ],
      steps: [
        ' Crisp edges with a soft center.',
        ' Served in a package of twelve pieces.',
        ' Can be consumed with milk on the side.',
      ],
      isGlutenFree: false,
      isVegan: false,
      isVegetarian: false,
      isLactoseFree: false,
      rating: 5.0),
  Meal(
    availability: Availability.Unvailable,
    rating: 2.4,
    id: 'm7',
    categories: [
      'c1',
    ],
    title: 'Patchi Box 84',
    Price: 5,
    imageUrl:
        "https://patchi.nyc3.cdn.digitaloceanspaces.com/patchi.com/public/data//products_gallery_600_600/6304e509b672d.jpg?v=4660?v=4660",
    duration: 60,
    ingredients: [
      'Eggs',
      'Milk',
      'Yogurt',
      'Oil',
      'Sugar',
      'Cacao',
      'Nescafe',
    ],
    steps: [
      ' Moisty and fluffy texture.',
      ' Minimum order of 6 pieces. (Additional pieces can be ordered).',
      ' Cupcakes can be stuffed with lotus, chocolate ganache and berry jam.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm8',
    categories: [
      'c2',
    ],
    title: 'Patchi Macaron Box',
    imageUrl: 'https://i.postimg.cc/D0vKBrFy/cake.jpg',
    duration: 90,
    Price: 5,
    ingredients: [
      'Brown Sugar',
      'White Sugar',
      'Eggs',
      'Bananas',
      'Yogurt',
      'Milk',
      'Butter',
      'Oil',
      'Baking Soda',
      'Baking Powder',
      'Vanilla',
      'Cinnamon',
      'Flour',
      'Chocolate Chips'
    ],
    steps: [
      ' Very soft and moist cake',
      ' Can be consumed with tea',
      ' Tastes both chocolatey with a kick of banana and cinnamon taste',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm9',
    categories: [
      'c1',
    ],
    title: 'Lindt OatMilk Salted Caramel',
    Price: 5,
    imageUrl:
        'https://www.lindtusa.com/media/catalog/product/0/0/00009542438692_front.jpg?quality=80&fit=bounds&height=500&width=500&canvas=500:500',
    duration: 45,
    ingredients: ["Milk", "Flour", "Sugar", "Butter", "Eggs", "Yeast", "Salt"],
    steps: [
      " Extremely soft and milkey.",
      " Tastes leanes more on the sweet side",
      " Enhance experience by adding nutella, honey or butter.",
      " Similar dough is used to make chocolate buns, cinnamon rolls and cheese buns."
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm10',
    categories: ['c1'],
    title: 'Lindt No Sugar Added Chocolate Candy Bar',
    Price: 5,
    imageUrl:
        'https://www.lindtusa.com/media/catalog/product/0/0/00009542043995_front.png?quality=80&fit=bounds&height=500&width=500&canvas=500:500',
    duration: 180,
    ingredients: [
      'Bread Flour',
      'Corn Starch',
      'Sugar',
      'Yeast',
      'Potato Water',
      'Olive Oil',
      'Mashed Potatoes',
    ],
    steps: [
      ' Soft texture both on the outside and the inside',
      ' Mild olive oil taste',
      ' Minimum 6, 6 cm pieces (customer can add pieces for an additional price)',
      ' Can be grilled and dipped with your favorite vegan dip (hommous) or non vegan dip',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm11',
    categories: ['c3'],
    title: 'Bacon Cheeseburger',
    imageUrl: 'https://i.postimg.cc/W304Q10h/burger.jpg',
    duration: 180,
    Price: 5,
    ingredients: [
      'Beef',
      'Mozzarella Cheese',
      'Tomatoes',
      'Thousand islands sauce',
      'Bacon',
      'Homemade Buns'
    ],
    steps: [
      ' Juicy burger with a 6 ounces meat grilled to perfection.',
      ' Burger is relatively large in size.',
      ' To be enjoyed with a beer or soft drink.',
      ' Fries can be included for an additional price.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm12',
    categories: ['c4'],
    title: 'Honey Mustard Chicken',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/TwvdqvBG/snadwuich vegie.jpg',
    duration: 120,
    ingredients: [
      'Chicken',
      'Lettuce',
      'Tomatoes',
      'Honey Mustard Sauce',
      'Mozzerella Cheese',
      'Pickles',
      'Homemade Ciabatta Bread'
    ],
    steps: [
      ' Tasty sandwich with a grilled chicken.',
      ' One serving per order.',
      ' Relatively medium sized and generously stuffed.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm13',
    categories: ['c4'],
    title: 'Frankfurter Sandwich',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/tCBg0fnt/franksandwich.jpg',
    duration: 120,
    ingredients: [
      'Ketchup',
      'Mustard',
      'Caramelized Onions',
      'Chips',
      'Frankfurter',
      'Pickles',
      'Homemade bun'
    ],
    steps: [
      ' One juicy sandwich per serving.',
      ' Can be paired with additional desired topings (jalapenos and cheese).',
      ' Relatively medium sized and generously stuffed.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm14',
    categories: ['c4'],
    title: 'Chicken Fajita',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/0jWhnhcc/tacos.jpg',
    duration: 120,
    ingredients: ['Chicken', 'Pepper', 'Onions ', 'Guacamole', 'Sour Creme'],
    steps: [
      ' Filling is packaged in a fajita wrap.',
      ' One fajita per serving.',
      ' Adjustments can be done accordingly to the customer\'s needs.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm15',
    categories: ['c5'],
    title: 'Rice Paper Rolls',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/wMHBHYkF/rice salad.jpg',
    duration: 60,
    ingredients: [
      "Thin rice noodles",
      "Carrot",
      "Cucumber",
      "Avocado ",
      "Peanuts",
      "Crab"
    ],
    steps: [
      ' 10 rolls per serving (up to 15).',
      ' Medium size per roll.',
      ' Ideally, food needs to be consumed when still fresh.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm16',
    categories: ['c5'],
    title: 'Rice Salad',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/1X9y2c9j/salad.jpg',
    duration: 20,
    ingredients: [
      'Rice',
      'Olive oil',
      'Lemon Juice',
      'Mixed Seasoning',
      'Garlic',
      "Tuna",
      "Bell Pepper",
      "Cucumber",
      "Corn",
      "Tomatoes",
      "Yogurt",
      "Mayo",
      "Dijon mustard"
    ],
    steps: [
      ' One medium sized salad per serving.',
      ' Ideally, food needs to be consumed two days after ordering at most.',
      ' Topings can be adjusted accordingly to the customer\'s needs.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    availability: Availability.Available,
    rating: 3.5,
    id: 'm17',
    categories: ['c5'],
    title: 'Chicken Rice Bowl',
    Price: 5,
    imageUrl: 'https://i.postimg.cc/g2CFfFd7/somesaladshit.jpg',
    duration: 120,
    ingredients: ['Chicken', 'Rice', 'Tomatoes', 'Corn', 'Mint', "cilantro"],
    steps: [
      ' One medium sized bowl per serving.',
      ' Rich in proteins',
      ' Chicken can be substituted with crispy chickpeas',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
];